#!/bin/bash

# =============================================
# Generic script to back up a directory
# to a remote over SSH. Server must be
# pre-configured to accept SSH connection
# from local user authenticated BY KEY
# (not password). 
# 
# By default, script "mirrors" $BACKUP_DIR to
# $REMOTE_DIR, deleting any unmatched files in
# the remote. Retain unmatched files on the
# remote by removing the --del flag.
#
# By default, non-excluded files in $BACKUP_DIR
# are backed up "directly" to $REMOTE_DIR, i.e.
# the contents are copied, but not the
# top-level directory itself. This behavior can
# be changed by removing the trailing slash
# after $BACKUP_DIR in the actual -rsync-
# command. See "Include/Exclude Pattern Rules"
# in the rsync(1) man page for more details.
# =============================================

BACKUP_DIR=XXXXX
EXCLUDES=XXXXX
REMOTE_USER=XXXXX
REMOTE_SERVER=X.X.X.X
REMOTE_DIR=XXXXX

rsync -avz -e 'ssh -p 2722'  --del --exclude-from=$EXCLUDES $BACKUP_DIR/ $REMOTE_USER@$REMOTE_SERVER:$REMOTE_DIR
