#!/bin/bash

BACKUP_DRIVE=/media/delamb/backup
BACKUP_DIR=$HOME/.dropbox-backup
TODAY=$(date '+%F')
LASTMONTH=$(date '+%F' -d '30 days ago')
THIS_LOG=$BACKUP_DIR/dropbox-backup_$TODAY.log

# create backup directory if it doesn't exist
if [ ! -d "$BACKUP_DIR" ] ; then
    mkdir $BACKUP_DIR
fi

# print datetime header to log
printf "DROPBOX BACKUP SYNC $(date '+%F %H:%M:%S')\n$(printf '=%.0s' ={1..39})\n" >> $THIS_LOG

# rsync Dropbox directory and log verbose output
rsync -avz $HOME/Dropbox $BACKUP_DRIVE >> $THIS_LOG

# print two blank lines, in case of multiple (manual) backups per day
printf "\n\n" >> $THIS_LOG

# delete log from 30 days ago, if it exists
if [ -f "$BACKUP_DIR/dropbox-backup_$LASTMONTH.log" ] ; then
    rm $BACKUP_DIR/dropbox-backup_$LASTMONTH.log
fi
